<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from landingpages/xml/schema/CRM/Landingpages/LandingPage.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:4b3d184213749cc413822d94cba90bc4)
 */
use CRM_Landingpages_ExtensionUtil as E;

/**
 * Database access object for the LandingPage entity.
 */
class CRM_Landingpages_DAO_LandingPage extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_landing_page';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique LandingPage ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * header
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $header_text;

  /**
   * footer
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $footer_text;

  /**
   * left
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $left_text;

  /**
   * right
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $right_text;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_landing_page';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Landing Pages') : E::ts('Landing Page');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique LandingPage ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_landing_page.id',
          'table_name' => 'civicrm_landing_page',
          'entity' => 'LandingPage',
          'bao' => 'CRM_Landingpages_DAO_LandingPage',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'header_text' => [
          'name' => 'header_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Header Text'),
          'description' => E::ts('header'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_landing_page.header_text',
          'table_name' => 'civicrm_landing_page',
          'entity' => 'LandingPage',
          'bao' => 'CRM_Landingpages_DAO_LandingPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'footer_text' => [
          'name' => 'footer_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Footer Text'),
          'description' => E::ts('footer'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_landing_page.footer_text',
          'table_name' => 'civicrm_landing_page',
          'entity' => 'LandingPage',
          'bao' => 'CRM_Landingpages_DAO_LandingPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'left_text' => [
          'name' => 'left_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Left Text'),
          'description' => E::ts('left'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_landing_page.left_text',
          'table_name' => 'civicrm_landing_page',
          'entity' => 'LandingPage',
          'bao' => 'CRM_Landingpages_DAO_LandingPage',
          'localizable' => 0,
          'add' => NULL,
        ],
        'right_text' => [
          'name' => 'right_text',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Right Text'),
          'description' => E::ts('right'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_landing_page.right_text',
          'table_name' => 'civicrm_landing_page',
          'entity' => 'LandingPage',
          'bao' => 'CRM_Landingpages_DAO_LandingPage',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'landing_page', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'landing_page', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
