-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_landing_page`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_landing_page
-- *
-- * Landing Page
-- *
-- *******************************************************/
CREATE TABLE `civicrm_landing_page` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique LandingPage ID',
  `header_text` text COMMENT 'header',
  `footer_text` text COMMENT 'footer',
  `left_text` text COMMENT 'left',
  `right_text` text COMMENT 'right',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
